# Generated by Django 5.1.1 on 2024-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
