# Generated by Django 5.1.1 on 2024-10-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='image_url',
        ),
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chef_images/'),
        ),
    ]
