# Generated by Django 5.1.1 on 2024-10-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recommendation', models.BooleanField(help_text='Would you recommend us to others?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
